version: '3.1'
services:
  db:
    image: postgres:13
    container_name: db
    environment:  
      - POSTGRES_DB=poldb
      - POSTGRES_PASSWORD=poldb
      - POSTGRES_USER=poldb
    ports:
      - "5433:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2024_pol.hidalgo@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: poldb
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data: